# Generated by the release workflow in shankar-sachin/canopy from
# packaging/homebrew/canopy-desktop.rb.in. Edit the template, not this file.
cask "canopy-desktop" do
  arch arm: "aarch64", intel: "x86_64"

  version "1.0.4"
  sha256 arm:   "8a03aa9e4ab63bd714458ff96ef710741ce8c6591b3165147081b38ec2b741bf",
         intel: "0019656b4f3e690d552fbaa75912545e89e08b23b2a63eae266c9617ff0aae47"

  url "https://github.com/shankar-sachin/canopy/releases/download/v#{version}/canopy-desktop-v#{version}-#{arch}-apple-darwin.dmg"
  name "canopy"
  desc "Beautiful, powerful git dashboard"
  homepage "https://shankar-sachin.github.io/canopy/"

  app "canopy.app"

  zap trash: "~/.config/canopy/desktop.json"

  caveats <<~EOS
    This cask isn't notarized by Apple yet since it's a release preview.
    If macOS says canopy can't be opened, open System Settings → Privacy &
    Security and click "Open Anyway", or run:
      xattr -dr com.apple.quarantine /Applications/canopy.app
  EOS
end
