# Generated by the release workflow in shankar-sachin/canopy from
# packaging/homebrew/canopy-desktop.rb.in. Edit the template, not this file.
cask "canopy-desktop" do
  arch arm: "aarch64", intel: "x86_64"

  version "1.0.12"
  sha256 arm:   "2784449d1c93b4da5096b5771cb346370cc136c8bddb1c088d93f5d0c8439ba5",
         intel: "f3eaef5d1082c87619f1f6fd3550e9ddaa547dbaa03f47c03c54cea852743c6f"

  url "https://github.com/shankar-sachin/canopy/releases/download/v#{version}/canopy-desktop-v#{version}-#{arch}-apple-darwin.dmg"
  name "canopy"
  desc "Friendly desktop app for git and GitHub"
  homepage "https://shankar-sachin.github.io/canopy/"

  app "canopy.app"

  zap trash: "~/.canopy/desktop.json"

  caveats <<~EOS
    This cask isn't notarized by Apple yet since it's a release preview.
    If macOS says canopy can't be opened, open System Settings → Privacy &
    Security and click "Open Anyway", or run:
      xattr -dr com.apple.quarantine /Applications/canopy.app
  EOS
end
