# Generated by the release workflow in shankar-sachin/canopy from
# packaging/homebrew/canopy-desktop.rb.in. Edit the template, not this file.
cask "canopy-desktop" do
  arch arm: "aarch64", intel: "x86_64"

  version "1.0.2"
  sha256 arm:   "7fa46eed919a68b38b96c90e1112f89f63fd37a812a5edd91047decab58389cc",
         intel: "6ac5ae56154bd95949e468b4fcc5eec515401d3b85a8b6098546c405a703e239"

  url "https://github.com/shankar-sachin/canopy/releases/download/v#{version}/canopy-desktop-v#{version}-#{arch}-apple-darwin.dmg"
  name "canopy"
  desc "Beautiful, powerful git dashboard"
  homepage "https://shankar-sachin.github.io/canopy/"

  app "canopy.app"

  zap trash: "~/.config/canopy/desktop.json"

  caveats <<~EOS
    This cask isn't notarized by Apple yet since it's a release preview.
    If macOS says canopy can't be opened, open System Settings → Privacy &
    Security and click "Open Anyway", or run:
      xattr -dr com.apple.quarantine /Applications/canopy.app
  EOS
end
