# Generated by the release workflow in shankar-sachin/canopy from
# packaging/homebrew/canopy.rb.in. Edit the template, not this file.
class Canopy < Formula
  desc "Beautiful, powerful git dashboard for your terminal"
  homepage "https://github.com/shankar-sachin/canopy"
  url "https://github.com/shankar-sachin/canopy/archive/refs/tags/v1.0.1.tar.gz"
  sha256 "d4c852343e59be30efe27632bb3348797a874c225686715fa146f079ba9137d2"
  license "MIT"
  head "https://github.com/shankar-sachin/canopy.git", branch: "main"

  depends_on "rust" => :build
  depends_on "git"

  def install
    system "cargo", "install", *std_cargo_args(path: "crates/canopy")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/canopy --version")
    assert_match "not inside a git repository", shell_output("#{bin}/canopy #{testpath}/nope 2>&1", 1)
  end
end
