# Generated by the release workflow in shankar-sachin/canopy from
# packaging/homebrew/canopy.rb.in. Edit the template, not this file.
#
# Installs the prebuilt binary from the GitHub release, so nothing is
# compiled (Homebrew on Linux needs no C compiler or Rust).
class Canopy < Formula
  desc "Git and GitHub in your terminal, everything from the keyboard"
  homepage "https://shankar-sachin.github.io/canopy/"
  version "1.0.8"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/shankar-sachin/canopy/releases/download/v1.0.8/canopy-v1.0.8-aarch64-apple-darwin.tar.gz"
      sha256 "4e8590415f3c6f12b7a9beb2cbe7c021031fcdf014db73195de5bd7b8e40ccac"
    end
    on_intel do
      url "https://github.com/shankar-sachin/canopy/releases/download/v1.0.8/canopy-v1.0.8-x86_64-apple-darwin.tar.gz"
      sha256 "31d0db06ff29a5915efd328a471d362673d4fbf298d7dfa92a7ffe03a484193f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/shankar-sachin/canopy/releases/download/v1.0.8/canopy-v1.0.8-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "4ff62d0cc9442e70626ba8a3004f9c33698b97a23d98ced8eff3d7e5f542b429"
    end
    on_intel do
      url "https://github.com/shankar-sachin/canopy/releases/download/v1.0.8/canopy-v1.0.8-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "cc859c6886fc3ecd8ecfada3f980f6f75feb431597e9b643e29cd89740a3ddbe"
    end
  end

  def install
    bin.install "canopy"
  end

  def caveats
    "Canopy needs git on your PATH (it runs your own git). GitHub pages also use the GitHub CLI (gh)."
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/canopy --version")
  end
end
